GET http://localhost:3000/garage
###
GET http://localhost:3000/garage?_limit=2
###
GET http://localhost:3000/garage?_page=1&_limit=2
###
GET http://localhost:3000/garage/1

###
POST http://localhost:3000/garage
Content-Type: application/json

{
  "name": "New Red Car",
  "color": "#ff0000"
}

###
PATCH http://localhost:3000/engine?id=2&status=started

